services:
  postgres:
    image: postgres:16-alpine
    container_name: mealbuddy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mealbuddy
      POSTGRES_USER: mealbuddy
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: mealbuddy-backend
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
      - DOCKER_DB_USERNAME=mealbuddy
      - DOCKER_DB_PASSWORD=strongpassword
      - DB_DATABASE=mealbuddy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: mealbuddy-frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: mealbuddy-nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
volumes:
  postgres_data:
